// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'skillsModel.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

SkillModel _$SkillModelFromJson(Map<String, dynamic> json) {
  return SkillModel(
    tagname: json['tagname'] as String,
    javaScript: json['javaScript'] as int,
    swift: json['swift'] as int,
    go: json['go'] as int,
    python: json['python'] as int,
    ruby: json['ruby'] as int,
    rust: json['rust'] as int,
    c: json['c'] as int,
    cPlusPlus: json['cPlusPlus'] as int,
    cSharp: json['cSharp'] as int,
    kotlin: json['kotlin'] as int,
    php: json['php'] as int,
    matlab: json['matlab'] as int,
    r: json['r'] as int,
    sql: json['sql'] as int,
    html: json['html'] as int,
    css: json['css'] as int,
    vbDotNet: json['vbDotNet'] as int,
    assemblyLevelLanguage: json['assemblyLevelLanguage'] as int,
    java: json['java'] as int,
    noSql: json['noSql'] as int,
    pearl: json['pearl'] as int,
    frontend: json['frontend'] as int,
    backend: json['backend'] as int,
    fullstack: json['fullstack'] as int,
    mobile: json['mobile'] as int,
    game: json['game'] as int,
    embedded: json['embedded'] as int,
    dataScientist: json['dataScientist'] as int,
    devops: json['devops'] as int,
    software: json['software'] as int,
    web: json['web'] as int,
    networkSecurity: json['networkSecurity'] as int,
    verilog: json['verilog'] as int,
    fpga: json['fpga'] as int,
    engineeringDesign: json['engineeringDesign'] as int,
    boardDesign: json['boardDesign'] as int,
    rubyOnRails: json['rubyOnRails'] as int,
    django: json['django'] as int,
    angular: json['angular'] as int,
    laravel: json['laravel'] as int,
    express: json['express'] as int,
    react: json['react'] as int,
    nodeJs: json['nodeJs'] as int,
    vueDotjs: json['vueDotjs'] as int,
    ember: json['ember'] as int,
    xamarin: json['xamarin'] as int,
    flutter: json['flutter'] as int,
    android: json['android'] as int,
    spring: json['spring'] as int,
    DotNetCore: json['DotNetCore'] as int,
    tensorFlow: json['tensorFlow'] as int,
    analyticalThinking: json['analyticalThinking'] as int,
    creativity: json['creativity'] as int,
    criticalThinking: json['criticalThinking'] as int,
    communicationSkill: json['communicationSkill'] as int,
    problemSolving: json['problemSolving'] as int,
    cyberSecurity: json['cyberSecurity'] as int,
    DL: json['DL'] as int,
    ML: json['ML'] as int,
    VrAr: json['VrAr'] as int,
    blockchain: json['blockchain'] as int,
    dataAnalytics: json['dataAnalytics'] as int,
    iot: json['iot'] as int,
    robotics: json['robotics'] as int,
    aerospace: json['aerospace'] as int,
    arduino: json['arduino'] as int,
    raspberryPi: json['raspberryPi'] as int,
    linux: json['linux'] as int,
    proteus: json['proteus'] as int,
    xilinx: json['xilinx'] as int,
    labview: json['labview'] as int,
    ltSpice: json['ltSpice'] as int,
    simulink: json['simulink'] as int,
    autoCad: json['autoCad'] as int,
    solidWork: json['solidWork'] as int,
    ansysFluent: json['ansysFluent'] as int,
    microsoftProject: json['microsoftProject'] as int,
    excel: json['excel'] as int,
    sketchUp: json['sketchUp'] as int,
    autoCadCivil3d: json['autoCadCivil3d'] as int,
    chemcad: json['chemcad'] as int,
  );
}

Map<String, dynamic> _$SkillModelToJson(SkillModel instance) =>
    <String, dynamic>{
      'tagname': instance.tagname,
      'javaScript': instance.javaScript,
      'swift': instance.swift,
      'go': instance.go,
      'python': instance.python,
      'ruby': instance.ruby,
      'rust': instance.rust,
      'c': instance.c,
      'cPlusPlus': instance.cPlusPlus,
      'cSharp': instance.cSharp,
      'kotlin': instance.kotlin,
      'php': instance.php,
      'matlab': instance.matlab,
      'r': instance.r,
      'sql': instance.sql,
      'html': instance.html,
      'css': instance.css,
      'vbDotNet': instance.vbDotNet,
      'assemblyLevelLanguage': instance.assemblyLevelLanguage,
      'java': instance.java,
      'noSql': instance.noSql,
      'pearl': instance.pearl,
      'frontend': instance.frontend,
      'backend': instance.backend,
      'fullstack': instance.fullstack,
      'mobile': instance.mobile,
      'game': instance.game,
      'embedded': instance.embedded,
      'dataScientist': instance.dataScientist,
      'devops': instance.devops,
      'software': instance.software,
      'web': instance.web,
      'networkSecurity': instance.networkSecurity,
      'verilog': instance.verilog,
      'fpga': instance.fpga,
      'engineeringDesign': instance.engineeringDesign,
      'boardDesign': instance.boardDesign,
      'rubyOnRails': instance.rubyOnRails,
      'django': instance.django,
      'angular': instance.angular,
      'laravel': instance.laravel,
      'express': instance.express,
      'react': instance.react,
      'nodeJs': instance.nodeJs,
      'vueDotjs': instance.vueDotjs,
      'ember': instance.ember,
      'xamarin': instance.xamarin,
      'flutter': instance.flutter,
      'android': instance.android,
      'spring': instance.spring,
      'DotNetCore': instance.DotNetCore,
      'tensorFlow': instance.tensorFlow,
      'analyticalThinking': instance.analyticalThinking,
      'creativity': instance.creativity,
      'criticalThinking': instance.criticalThinking,
      'communicationSkill': instance.communicationSkill,
      'problemSolving': instance.problemSolving,
      'cyberSecurity': instance.cyberSecurity,
      'DL': instance.DL,
      'ML': instance.ML,
      'VrAr': instance.VrAr,
      'blockchain': instance.blockchain,
      'dataAnalytics': instance.dataAnalytics,
      'iot': instance.iot,
      'robotics': instance.robotics,
      'aerospace': instance.aerospace,
      'arduino': instance.arduino,
      'raspberryPi': instance.raspberryPi,
      'linux': instance.linux,
      'proteus': instance.proteus,
      'xilinx': instance.xilinx,
      'labview': instance.labview,
      'ltSpice': instance.ltSpice,
      'simulink': instance.simulink,
      'autoCad': instance.autoCad,
      'solidWork': instance.solidWork,
      'ansysFluent': instance.ansysFluent,
      'microsoftProject': instance.microsoftProject,
      'excel': instance.excel,
      'sketchUp': instance.sketchUp,
      'autoCadCivil3d': instance.autoCadCivil3d,
      'chemcad': instance.chemcad,
    };
